name: OtakuLibrary
description: Flutter project for Otaku Library

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.3.0
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: 5.0.2
  flutter_image_compress: ^1.1.3
  archive: ^3.3.6
  path_provider: ^2.0.12
  form_field_validator: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.5
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: assets/splash/splash.png
  android: true
  ios: true

flutter:

  uses-material-design: true
  assets:
    - assets/splash/splash.png
    - assets/icon/
    - assets/fonts/
    - .env
    - assets/cbz/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic